services:
  - type: web
    name: esi-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: SECRET_KEY
        scope: run
      - key: CLOUDINARY_CLOUD_NAME
        scope: run
      - key: CLOUDINARY_API_KEY
        scope: run
      - key: CLOUDINARY_API_SECRET
        scope: run
      - key: FRONTEND_URL
        scope: run
