services:
  - type: web
    name: esi-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        scope: run
      - key: SECRET_KEY
        scope: run
      - key: CLOUDINARY_CLOUD_NAME
        scope: run
      - key: CLOUDINARY_API_KEY
        scope: run
      - key: CLOUDINARY_API_SECRET
        scope: run
      - key: FRONTEND_URL
        scope: run
